export interface  DenunciaTerceiros //tabela do banco
{
    $id;
    $nomeVitima;
    $dataDeNascVitima;
    $telefoneVitima;
    $cpfVitima;
    $rgVitima;
    $emailVitima;
    $enderecoVitima;
    $relacaoDV;
    $tipoDenuncia;
    $nomeDenunciado;
    $dataDeNascDenunciado;
    $enderecoDenunciado;
    $telefoneDenunciado;
    $RgDenunciado;
    $cpfDenunciado;
    $emailDenunciado;
    $enderecoOcorrido;
    $dataOcorrido;
    $frequencia;
    $relacaoVA;
    $localDeTrabalho;
    $descricaoAgressor;
    $descricaoOcorrido;
    $id_user;

}